### ISSUE TITLE
BTB bot crashes the trading bot if internet outage

### ISSUE THREAD

**Issue by jbrepogmailcom** [lorcalhost/BTB-manager-telegram#260]
Hello. If I run btb trading bot without BTB and there is internet outage, the binance trading bot resumes after the outage and continues working. If the trading bot is launched from BTB and there is internet outage, the BTB crashes and subsequently it also crashes the trading bot. When internet becomes available again, the BTB and trading bot do not resume and stay crashed. Or at least the trading bot stays stopped and needs to be restarted "manually" through BTB's "START BOT" command.

Also the telegram user is not informed that trading bot is not running anymore.

**Comment by titulebolide** [comment]
Hello,

Thanks for this insight, I've already noticed that the bot could randomly stop but never investigated why. I'll be looking into that, thanks for reporting.

**Comment by titulebolide** [comment]
So
In this winter batch of updates, i've added a system to forward error logs to telegram,and help the manager handle gracefully its error instead of crashing. The thing is even we try to handle gracefully an error (such as internet outage), the error forwarding (included in the handling) might crash as well which finally crashes the bot. I've put up a commit tonight in an attempt to fix this.
I close this issue for now, don't hesitate at all to reopen it if the problem persists.
